### ISSUE TITLE
Suppression of write_env(..)  calls is not possible anymore after removal of `Options` struct

### ISSUE THREAD

**Issue by soenkeliebau** [lukaslueg/built#62]
The `Options` struct had a flag `env` which allowed suppressing this a call: https://github.com/lukaslueg/built/blob/4cce4dcecb264ac8f5a0f057e045bd06506d838e/src/lib.rs#L1001

It looks to me like there is no equivalent setting any more, after switching the crate to use features for configuration.

In our dev workflow we use crate2nix for shortened feedback loops, and this call causes our build to fail with the  error shown below, because we are not using cargo and don't have those env vars available.

We have fixed it for our build by [forking](https://github.com/lukaslueg/built/commit/8df51061dc78041ada22350be273f9c7ef1ae935) and patching our dependency, but would obviously like to go back to not having to maintain a fork for ourselves.

Would you be willing to accept a PR that introduces something like a `skip_environment` flag which gates this line of code?

```
thread 'main' panicked at src/environment.rs:53:9:
Missing expected environment variable "CARGO_PKG_LICENSE"
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_failed
   3: core::option::Option<T>::expect
             at /rustc-1.73.0-src/library/core/src/option.rs:898:21
   4: built::environment::EnvironmentMap::write_env
             at /built-c65381b/src/environment.rs:53:9
   5: built::write_built_file_with_opts
             at /built-c65381b/src/lib.rs:369:5
   6: build_script_build::main
             at ./build.rs:5:5
   7: core::ops::function::FnOnce::call_once
             at /build/rustc-1.73.0-src/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: builder for '/nix/store/4razldnhkhkjfwxn00fra536wzzk738i-rust_stackable-hbase-operator-0.0.0-dev.drv' failed with exit code 101;
       last 10 log lines:
       >              at /rustc-1.73.0-src/library/core/src/option.rs:898:21
       >    4: built::environment::EnvironmentMap::write_env
       >              at /built-c65381b/src/environment.rs:53:9
       >    5: built::write_built_file_with_opts
       >              at /built-c65381b/src/lib.rs:369:5
       >    6: build_script_build::main
       >              at ./build.rs:5:5
       >    7: core::ops::function::FnOnce::call_once
       >              at /build/rustc-1.73.0-src/library/core/src/ops/function.rs:250:5
       > note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by soenkeliebau** [comment]
As per the discussion in https://github.com/lukaslueg/built/pull/63 closing this as WONTFIX
