### ISSUE TITLE
thread 'main' panicked at 'Box<Any>', built/src/lib.rs:337:18

### ISSUE THREAD

**Issue by jonathonf** [lukaslueg/built#7]
### Platform
**Linux** (64-bit, Manjaro; 64-bit, Ubuntu 16.04; 64-bit, Debian 9)
**Shell:** zsh, bash
**rustc:** 1.22.1
**cargo:** 0.23.0

(rustc and cargo installed via rustup)

### Issue
The `example_project` compiles correctly but other usage does not, failing with

```
error: failed to run custom build command for `built-test v0.1.0 (file:///dev/shm/built-test)`
process didn't exit successfully: `/dev/shm/built-test/target/release/build/btest-9d69b834929d02ed/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Box<Any>', /home/jonathon/.cargo/registry/src/github.com-1ecc6299db9ec823/built-0.2.0/src/lib.rs:339:18
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

### Minimal-working example

```
$ cargo new built-test --bin
```

#### Cargo.toml
```
[package]
name = "built-test"
version = "0.1.0"
authors = ["Me <me@me.me>"]
build = "build.rs"

[dependencies]
built = "0.2.0"
[build-dependencies]
built = "0.2.0"
```

#### build.rs
```
extern crate built;
fn main() {
    built::write_built_file().expect("Failed to acquire build-time information");
}
```

```
$ RUST_BACKTRACE=1 cargo build
   Compiling btest v0.1.0 (file:///dev/shm/built-test)
error: failed to run custom build command for `built-test v0.1.0 (file:///dev/shm/built-test)`
process didn't exit successfully: `/dev/shm/built-test/target/debug/build/btest-488b555995f5425f/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Box<Any>', /home/jonathon/.cargo/registry/src/github.com-1ecc6299db9ec823/built-0.2.0/src/lib.rs:339:18
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:69
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:58
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: built::write_git_version
             at /home/jonathon/.cargo/registry/src/github.com-1ecc6299db9ec823/built-0.2.0/src/lib.rs:339
   7: built::write_built_file_with_opts
             at /home/jonathon/.cargo/registry/src/github.com-1ecc6299db9ec823/built-0.2.0/src/lib.rs:807
   8: built::write_built_file
             at /home/jonathon/.cargo/registry/src/github.com-1ecc6299db9ec823/built-0.2.0/src/lib.rs:835
   9: build_script_build::main
             at ./build.rs:3
  10: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  11: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  12: main
  13: __libc_start_main
  14: _start
```

### See also
https://github.com/jwilm/alacritty/issues/917

**Comment by lukaslueg** [comment]
I see where it panics, can't reproduce on macOS, though. Downloading this manjaro stuff and check out.

**Comment by lukaslueg** [comment]
This seems to be a problem with some versions of libgit. One can reproduce with an initialized yet empty git repository. For now errors from libgit are silenced. Try again.

**Comment by jonathonf** [comment]
My example above now compiles correctly!

And so does `alacritty`. Yay! Now off to do a PR...

:grinning:
